version: "3"
services:
  typo3:
    build: ./docker
    ports:
      - "80:80"
    environment:
      DB_NAME: typo3
      DB_USER: admin
      DB_PASS: "Pjbc4DD4rGp7pkSm"
      DB_HOST: "typo3-db"
      DB_PORT: "3306"
    volumes:
      - fileadmin:/var/www/html/fileadmin
      - typo3conf:/var/www/html/typo3conf
      - uploads:/var/www/html/uploads
  typo3-db:
    image: tutum/mysql:5.5
    environment:
      MYSQL_PASS: "Pjbc4DD4rGp7pkSm"
    ports:
      - 3306:3306
volumes:
  database:
  fileadmin:
  typo3conf:
  uploads:
